version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - express
      - mosquitto
  express:
    container_name: express
    build: ./express
    ports:
      - '3000:3000'
    links:
      - mongo
      - mosquitto
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
  mosquitto:
    container_name: mosquitto
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
